### PR TITLE
Add support for cache namespace

### PR DESCRIPTION
**Pull request by jcberquist**
Also adds back support for idle parameter in put() method to support
session timeouts, including a workaround for new sessions being cached
with an idle value of -1

### CODE REVIEW

**Comment by MordantWastrel** [comment]
@jcberquist This would be a great feature to have! Why was this closed?

**Comment by jcberquist** [comment]
@MordantWastrel I closed it after the recent updates to the extension. I would have had to redo it to make it work again, and it didn't seem likely to be accepted at this point, given how long it had been sitting here :)

Further, the changes were a bit problematic for my use cases since the extension has moved to using ObjectInputStream/ObjectOutputStream for serialization - that improves performance I am sure, but it prevents interop with other (non Lucee/Java) redis clients, which I need. So I decided that while I would continue to keep an eye on this extension, I would just continue using my own fork for the present.

**Comment by MordantWastrel** [comment]
@michaeloffner Can you weigh in on this (or else on #6 which is pretty much the same question)?

**Comment by MordantWastrel** [comment]
@michaeloffner If this isn't going to be added, can we update the README so that it doesn't indicate that namespace is supported?

**Pull request closed without merging**
